- common/common-onprem.ps1
- common/common.sh
- menus/master.ps1
- onprem/main.sh
- onprem/setupworker.sh
> add prerelease flag to setupworker.sh

- common/troubleshooting-menu.ps1
- menus/master.ps1
> simplify top level menu

- common/common-kube.ps1
- common/common-onprem.ps1
- common/common.ps1
- dashboard/index.json
- dashboard/ingress/http/grafana.yaml
- developer/createhyperv.ps1
- nlp/ingress/tcp/mysqlserver.internal.yaml
- nlp/ingress/tcp/mysqlserver.public.yaml
> add call to show nodes at the end of setting up a worker

- azure/main.ps1
- nlp/pods/jobserver.yaml
- nlp/pods/nlpwebserver.yaml
> change data field to value for nlpweb-external-url

- azure/main.ps1
> read common-azure.ps1 from url

- common/common-azure.ps1
- deployments/prod-kub-hcut.json
> add back in code to set host files

- azure/main.ps1
- common/common-azure.ps1
- common/common.ps1
> fix loop in RestartVMs

- nlp/pods/mysqlserver.yaml
- nlp/pods/solrserver.yaml
> comment out readiness probes for now

- common/troubleshooting-menu.ps1
> fix troubleshooting menu

- common/common-kube.ps1
- loadbalancer/index.json
> run installstack after setting up loadbalancer

- common/common-kube.ps1
- common/common.ps1
> show what config file is being downloaded

- common/common-kube.ps1
- loadbalancer/index.json
> remove configmaps on loadbalancer

- common/common.ps1
- loadbalancer/pods/traefik-azure.both.yaml
- loadbalancer/pods/traefik-azure.external.ssl.yaml
- loadbalancer/pods/traefik-azure.external.yaml
- loadbalancer/pods/traefik-azure.internal.ssl.yaml
- loadbalancer/pods/traefik-azure.internal.yaml
> fix GetDNSCommands for tcp services to use the IP of the tcp service

- common/common-azure.ps1
> setup crontab to restart kube dns if it fails

- common/common.ps1
> fix code for SetupCronTab

- common/common.ps1
> replace comma with space for whitelist

- azure/main.ps1
- common/common-azure.ps1
- common/common.ps1
> handle multiple IP addresses in whitelist

- azure/main.ps1
- common/common-kube.ps1
- loadbalancer/ingress/http/dashboard.external.yaml
- loadbalancer/services/cluster/dashboard.external.yaml
> fix traefik dashboard for external services

- common/common-kube.ps1
- common/common-onprem.ps1
> move WriteToConsole function to common-kube.ps1

- common/product-menu.ps1
> fix namespace param

- azure/main.ps1
- deployments/fabrickubernetes.json
- deployments/fabrickubernetes2..json
> added menu item to get DNS entries

- 2018-05-14-17-32-createacscluster.txt
- common/common.ps1
- deployments/fabrickubernetes2.json
- deployments/prod-kub-hcut.json
> wait for internal load balancer to be assigned IP

- azure/acs.template.linuxwindows.json
- common/common-azure.ps1
- common/common-onprem.ps1
- deployments/sharedkubernetes.json
> try a different way of testing if mount was successful

- common/common-onprem.ps1
> show lastexitcode for kubeadm reset

- common/common-onprem.ps1
> increment version

- common/common-onprem.ps1
> remove sec=ntlm and add vers=2.1 to fix the issue with mounting

- common/common-onprem.ps1
> change password to pass for mount

- common/product-menu.ps1
> add isAzure around block to wait for load balancers

- common/common-azure.ps1
- common/common-kube.ps1
> update version number

- common/common-azure.ps1
> show error code by acs-engine

- nlp/pods/jobserver.yaml
Reverts HealthCatalyst/dos.install#56
> Revert "Changed the jobserver pod configuration to a cronjob"

- azure/main.ps1
> import module by specifying version

- azure/main.ps1
> check verison of module before installing

- azure/dos.ps1
- runlocal.ps1
> fix path to main.ps1

- azure/main.ps1
> add Import-Module

- azure/main.ps1
> increment versions

- menus/onprem-menu.ps1
> increment version of onprem package
